on:
  push:
    branches:
      - main
  schedule:
    - cron: "5 11,16,19 * * *"

jobs:
  deploy-production:
    name: Deploy Production
    runs-on: docker
    timeout-minutes: 3
    steps:
      - name: Checkout Repository
        timeout-minutes: 0.25
        uses: https://github.com/actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Mise Install
        timeout-minutes: 0.25
        uses: https://github.com/jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          version: 2026.2.0
      - name: Project Setup
        timeout-minutes: 2
        run: deno task setup
      - name: Create CI Artefacts
        timeout-minutes: 0.25
        run: deno task create-ci-artefacts
      - name: Deploy Production
        timeout-minutes: 0.25
        run: |
          deno deploy \
            --org=100terres \
            --app=widgets \
            --token=${{ secrets.DENO_DEPLOY_PERSONAL_ACCESS_TOKEN }} \
            --prod \
            --no-wait
